In [ ]:
import itertools
import numpy as np

# Define the assumptions and restrictions
max_workdays_per_week = 3
min_consecutive_off_days = 2
max_consecutive_workdays = 4

# Function to check if a binary pattern adheres to the assumptions
def is_valid_pattern(pattern):
    consecutive_off_days = 0
    consecutive_workdays = 0
    workdays_per_week = 0

    for bit in pattern:
        if bit == 0:  # Off day
            consecutive_off_days += 1
            consecutive_workdays = 0
        else:  # Workday
            consecutive_off_days = 0
            consecutive_workdays += 1
            workdays_per_week += 1

        # Check assumptions
        if workdays_per_week > max_workdays_per_week:
            return False
        if consecutive_off_days < min_consecutive_off_days and consecutive_workdays > max_consecutive_workdays:
            return False

    return True

# Generate all 7-bit binary patterns
binary_patterns = list(itertools.product([0, 1], repeat=7))

# Filter patterns that adhere to assumptions 1 to 3
valid_h_patterns = [pattern for pattern in binary_patterns if is_valid_pattern(pattern)]

valid_h_patterns.pop(0)
valid_h_patterns.pop(35)


# Display the valid h-patterns
for i, pattern in enumerate(valid_h_patterns):
    print(f"Pattern {i+1}: {pattern}")

h_patterns=valid_h_patterns

Pattern 1: (0, 0, 0, 0, 0, 0, 1)
Pattern 2: (0, 0, 0, 0, 0, 1, 0)
Pattern 3: (0, 0, 0, 0, 0, 1, 1)
Pattern 4: (0, 0, 0, 0, 1, 0, 0)
Pattern 5: (0, 0, 0, 0, 1, 0, 1)
Pattern 6: (0, 0, 0, 0, 1, 1, 0)
Pattern 7: (0, 0, 0, 0, 1, 1, 1)
Pattern 8: (0, 0, 0, 1, 0, 0, 0)
Pattern 9: (0, 0, 0, 1, 0, 0, 1)
Pattern 10: (0, 0, 0, 1, 0, 1, 0)
Pattern 11: (0, 0, 0, 1, 0, 1, 1)
Pattern 12: (0, 0, 0, 1, 1, 0, 0)
Pattern 13: (0, 0, 0, 1, 1, 0, 1)
Pattern 14: (0, 0, 0, 1, 1, 1, 0)
Pattern 15: (0, 0, 1, 0, 0, 0, 0)
Pattern 16: (0, 0, 1, 0, 0, 0, 1)
Pattern 17: (0, 0, 1, 0, 0, 1, 0)
Pattern 18: (0, 0, 1, 0, 0, 1, 1)
Pattern 19: (0, 0, 1, 0, 1, 0, 0)
Pattern 20: (0, 0, 1, 0, 1, 0, 1)
Pattern 21: (0, 0, 1, 0, 1, 1, 0)
Pattern 22: (0, 0, 1, 1, 0, 0, 0)
Pattern 23: (0, 0, 1, 1, 0, 0, 1)
Pattern 24: (0, 0, 1, 1, 0, 1, 0)
Pattern 25: (0, 0, 1, 1, 1, 0, 0)
Pattern 26: (0, 1, 0, 0, 0, 0, 0)
Pattern 27: (0, 1, 0, 0, 0, 0, 1)
Pattern 28: (0, 1, 0, 0, 0, 1, 0)
Pattern 29: (0, 1, 0, 0, 0, 1, 1)
Pattern 30: (0, 1, 0, 0

In [ ]:
import math

# Define the labor demand vector R (replace with your specific values)
R = [5, 5, 5, 5, 5, 3, 3, 5, 5, 5 ,5, 8, 7, 3, 6, 6, 7, 7, 5, 3, 3]

T=len(R)

# Calculate rmax (the maximum number of employees needed)
rmax = max(R)

# Initialize rceil as an empty list
rceil = []

# Calculate rceil for each week (j)
for j in range(math.ceil(len(R) / 7)):
    start_day = j * 7
    end_day = min((j + 1) * 7, len(R))
    weekly_sum = sum(R[start_day:end_day])
    rceil.append(math.ceil(weekly_sum / 3))

# Calculate the minimum number of employees (W)
W = max(max(rceil), rmax)

print(f"rmax: {rmax}")
print(f"rceil: {rceil}")
print(f"Minimum number of employees (W): {W}")


rmax: 8
rceil: [11, 13, 13]
Minimum number of employees (W): 13


In [ ]:
len(R)

21

In [ ]:
import itertools

N_v=[]
vertical_patterns = []

# Calculate and store the vertical patterns for each time t
for t in range(len(R)):
    # Calculate the number of vertical patterns at time t
    N_v_t = len(list(itertools.combinations(range(W), R[t])))

    # Store the number of vertical patterns for this time t
    N_v.append(N_v_t)

    # Generate and store the vertical patterns
    combinations = list(itertools.combinations(range(W), R[t]))
    vertical_patterns_t=np.zeros((len(combinations),W))
    for i in range(len(combinations)):
      for j in combinations[i]:
        vertical_patterns_t[i][j]=1

    vertical_patterns.append(vertical_patterns_t)

# Display the number of vertical patterns and some examples of patterns
for t in range(len(R)):
    print(f"Time {t + 1}: N_v(t) = {N_v[t]}")
    print(f"Vertical Patterns: {vertical_patterns[t]}")

# You can access N_v[t] for the number of patterns at a specific time t
# You can access vertical_patterns[t] for the patterns at a specific time t




Time 1: N_v(t) = 1287
Vertical Patterns: [[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
Time 2: N_v(t) = 1287
Vertical Patterns: [[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
Time 3: N_v(t) = 1287
Vertical Patterns: [[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
Time 4: N_v(t) = 1287
Vertical Patterns: [[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
Time 5: N_v(t) = 1287
Vertical Patterns: [[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
Time 6: N_v(t) 

In [ ]:
print(N_v)

[1287, 1287, 1287, 1287, 1287, 286, 286, 1287, 1287, 1287, 1287, 1287, 1716, 286, 1716, 1716, 1716, 1716, 1287, 286, 286]


In [ ]:
# Define a function to check if there are more than 3 consecutive workdays in a week
def con_check(te):
    f = False
    for i in range(0, len(te), 7):
        if sum(te[i:i+7]) > 3:
            f = True
            break
    return f

# Define a function to compute the cost based on work assignment
def cost_function(temp, c):
    cost = 0
    count = 0
    for i in range(temp.shape[0]):
        # Check if the week violates consecutive workdays constraint
        if not con_check(temp[i]):
            for j in range(1, temp.shape[1] + 2):
                if j == temp.shape[1] + 1 or temp[i][j - 1] == 0:
                    if count == 1:
                        if (j - 1) % 7 == 0 or j % 7 == 0:
                            cost += c[1]
                        else:
                            cost += c[0]
                    elif count == 2:
                        if (j - 1) % 7 == 0:
                            cost += c[1] + c[2]
                        else:
                            cost += 2 * c[0]
                    elif count == 3:
                        if (j - 2) % 7 == 0:
                            cost += c[1] + c[2] + c[3]
                        elif j % 7 == 0:
                            cost += 2 * c[0] + c[5]
                        else:
                            cost += 3 * c[0]
                    elif count == 4:
                        if (j - 3) % 7 == 0:
                            cost += c[1] + c[2] + c[3] + c[6]
                        elif (j - 4) % 7 == 0:
                            cost += c[1] + c[0] + c[0] + c[7]
                        else:
                            cost += 999999
                    elif count >= 4:
                        cost += 999999
                    count = 0
                else:
                    count += 1
        else:
            cost += 999999
    return cost

# Initialize P matrix to store work assignment (W x T)
P = np.zeros((W, T))

# Define the cost coefficients C
C = [1, 1.5, 2, 1.25, 1.5, 2, 1.5, 1.5]

min_cost = 99999
temp = P

# Iterate through time periods (T) and vertical patterns (N_v)
for i in range(len(R)):
    for j in range(N_v[i]):
        temp[:, i] = vertical_patterns[i][j]

        if i == 0 and j == 0:
            cost = cost_function(temp, C)

        if cost < min_cost:
            P = temp
            min_cost = cost
        else:
            temp = P

    min_cost = 99999
total_cost=cost_function(P, C)

In [ ]:
vertical_patterns[0].shape

(1287, 13)

In [ ]:

print("COST: ",total_cost)


print("\n\nWork Assignment: \n")
for i in range(len(P)):
  print("%d"%(i+1),end="\t")
  for j in P[i]:
    print(j,end="  ")
  print()

COST:  113.5


Work Assignment: 

1	1  1  0  0  1  0  0  1  1  0  0  1  0  0  1  1  0  0  1  0  0  
2	1  1  0  0  1  0  0  1  1  0  0  1  0  0  1  1  0  0  1  0  0  
3	1  1  0  0  1  0  0  1  1  0  0  1  0  0  1  1  0  0  1  0  0  
4	1  1  0  0  1  0  0  1  1  0  0  1  0  0  1  1  0  0  1  0  0  
5	1  1  0  0  1  0  0  1  1  0  0  1  0  0  1  1  0  0  1  0  0  
6	0  0  1  1  0  0  1  0  0  1  1  0  0  1  1  1  0  1  0  0  0  
7	0  0  1  1  0  0  1  0  0  1  1  0  1  0  0  0  1  1  0  0  1  
8	0  0  1  1  0  0  1  0  0  1  1  0  1  0  0  0  1  1  0  0  1  
9	0  0  1  1  0  0  0  0  0  1  1  0  1  0  0  0  1  1  0  0  1  
10	0  0  1  1  0  0  0  0  0  1  1  0  1  0  0  0  1  1  0  1  0  
11	0  0  0  0  0  1  0  0  0  0  0  1  1  1  0  0  1  1  0  1  0  
12	0  0  0  0  0  1  0  0  0  0  0  1  1  1  0  0  1  1  0  1  0  
13	0  0  0  0  0  1  0  0  0  0  0  1  1  0  0  0  1  0  0  0  0  


In [ ]:
P=[
    [1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0],
[1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0],
[1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0],
[1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0],
[1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0],
[0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0],
[0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1],
[0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1],
[0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1],
[0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0],
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0],
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0],
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0]
]

P=np.array(P)
total_cost = 113.5